name: Treefy - CI/CD Publish

on:
  push:
    branches: [main]

env:
  NODE_OPTIONS: '--max_old_space_size=8192'
  REGION: ${{ secrets.REGION }}
  USERPOOLID: ${{ secrets.USERPOOLID }}
  IDENTITYPOOLID: ${{ secrets.IDENTITYPOOLID }}
  USERPOOLWEBCLIENTID: ${{ secrets.USERPOOLWEBCLIENTID }}
  API_BASE_URL: ${{ secrets.API_BASE_URL }}
  NODE_ENV: production

jobs:
  Publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies 📦
        run: npm ci --legacy-peer-deps

      - name: Publish app 🚀
        run: expo publish --non-interactive
