name: Treefy - CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Node-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './package-lock.json'
      - run: npm install
      - name: Install dependencies 📦
      - run: npm run prettier
      - name: Run prettier 💅
      - run: npm run lint
      - name: Run linter ✔️
      - run: npm run test:unit:ci
      - name: Run unit tests 🧪
