on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Tests-unit:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/node-build.yml
    steps:
      - name: Run unit tests 🧪
        run: npm run test:unit:ci
